import { auth } from "@/auth";
import { getDBUserById } from "@/db/users";
import { SportsFootball } from "@mui/icons-material";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { redirect } from "next/navigation";
import NewUserForm from "@/components/new-user-form";
import NextLink from "next/link";
import Link from "@mui/material/Link";

export default async function NewUser() {
  const session = await auth();
  if (!session?.user?.id) {
    return redirect("/");
  }

  const dbUser = await getDBUserById(session.user.id!);
  if (!dbUser) {
    console.error(
      `user with id ${session.user.id} from session not found in db`
    );

    return redirect("/");
  }

  return (
    <main>
      <Stack
        direction={"row"}
        justifyContent={"center"}
        alignItems={"center"}
        height={"100%"}
      >
        <Stack
          direction={"column"}
          justifyContent={"center"}
          alignItems={"center"}
          sx={{
            padding: { xs: 4, sm: 8 },
            gap: { xs: 2, sm: 4 },
          }}
        >
          <Typography variant="h2">
            Welcome to Pix <SportsFootball fontSize="large" />
          </Typography>

          <Typography variant="body1">
            Please set a username. This can be changed later on in your profile
            settings. Or you can proceed with an autogenerated username.
          </Typography>

          <NewUserForm />

          <Link component={NextLink} href={"/"}>
            Proceed with an autogenerated username
          </Link>
        </Stack>
      </Stack>
    </main>
  );
}
